"""add_audit_request_gdpr_models

Revision ID: 591f975d7c95
Revises: 
Create Date: 2026-04-30 09:05:51.630549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591f975d7c95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GdprDataExport',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('studentId', sa.String(), nullable=False),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('requestedAt', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'READY', 'EXPIRED', 'ERROR', name='gdprstatus'), nullable=False),
    sa.Column('generatedAt', sa.DateTime(), nullable=True),
    sa.Column('exportData', sa.LargeBinary(), nullable=True),
    sa.Column('expiresAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizationId'], ['Organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studentId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('GdprDataExport', schema=None) as batch_op:
        batch_op.create_index('ix_gdprexport_student_status', ['studentId', 'status'], unique=False)

    op.create_table('GdprForgetRequest',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('studentId', sa.String(), nullable=True),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='gdprforgetstatus'), nullable=False),
    sa.Column('approvedBy', sa.String(), nullable=True),
    sa.Column('approvedAt', sa.DateTime(), nullable=True),
    sa.Column('requestedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approvedBy'], ['User.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizationId'], ['Organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studentId'], ['User.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('GdprForgetRequest', schema=None) as batch_op:
        batch_op.create_index('ix_gdprforget_org_status', ['organizationId', 'status'], unique=False)

    op.create_table('AuditRequest',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('originalAttemptId', sa.String(), nullable=True),
    sa.Column('enrollmentId', sa.String(), nullable=True),
    sa.Column('requestedBy', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWING', 'CONFIRMED', 'REEVALUATED', 'REJECTED', name='auditstatus'), nullable=False),
    sa.Column('reviewedBy', sa.String(), nullable=True),
    sa.Column('reviewedAt', sa.DateTime(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('filedAfterClose', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enrollmentId'], ['Enrollment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizationId'], ['Organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['originalAttemptId'], ['Attempt.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requestedBy'], ['User.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewedBy'], ['User.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('AuditRequest', schema=None) as batch_op:
        batch_op.create_index('ix_auditrequest_attempt', ['originalAttemptId'], unique=False)
        batch_op.create_index('ix_auditrequest_enrollment', ['enrollmentId'], unique=False)
        batch_op.create_index('ix_auditrequest_org_status', ['organizationId', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AuditRequest', schema=None) as batch_op:
        batch_op.drop_index('ix_auditrequest_org_status')
        batch_op.drop_index('ix_auditrequest_enrollment')
        batch_op.drop_index('ix_auditrequest_attempt')

    op.drop_table('AuditRequest')
    with op.batch_alter_table('GdprForgetRequest', schema=None) as batch_op:
        batch_op.drop_index('ix_gdprforget_org_status')

    op.drop_table('GdprForgetRequest')
    with op.batch_alter_table('GdprDataExport', schema=None) as batch_op:
        batch_op.drop_index('ix_gdprexport_student_status')

    op.drop_table('GdprDataExport')
    # ### end Alembic commands ###
